# Detailed descriptions of these parameters can be found at http://www.ros.org/wiki/costmap_2d
local_costmap:
   global_frame: odom
   robot_base_frame: robot_footprint
   update_frequency: 10.0
   publish_frequency: 5.0
   width: 5.0
   height: 5.0
   resolution: 0.1
   static_map: false
   rolling_window: true
   transform_tolerance: 0.2
   plugins:
     - {name: static_layer,            type: "costmap_2d::StaticLayer"}
     - {name: obstacle_layer,          type: "costmap_2d::VoxelLayer"}
     - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}
