# Detailed descriptions of these parameters can be found at http://wiki.ros.org/costmap_2d
global_costmap:
   global_frame: map
   robot_base_frame: robot_footprint
   update_frequency: 5.0 # 50.0
   publish_frequency: 5.0 # 50.0
   width: 40.0
   height: 40.0
   resolution: 0.1 # 0.05
   static_map: true
   rolling_window: false
   # Added
   plugins:
     - {name: static_layer,            type: "costmap_2d::StaticLayer"}
     - {name: obstacle_layer,          type: "costmap_2d::VoxelLayer"}
     - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}

